// Battle Brothers Event Requirements Database
// Total events: 35

this.EventRequirements <- [
    {
        EventID = "event.arena_tournament",
        FileName = "arena_tournament_event.nut",
        RequiredDLC = ["Blazing Deserts"],
        SettlementSituation = "Must have Arena Tournament Settlement Situation",
        SettlementType = "Southern",
        TileRequirements = { Road = "OnRoad", OnOrBelowYLine = 60 },
    },
    {
        EventID = "event.belly_dancer",
        FileName = "belly_dancer_event.nut",
        MaxDistanceFromSettlement = 4,
        MinimumCrowns = 751,
        NumberOfOpenRosterSlots = 1,
        RequiredDLC = ["Blazing Deserts"],
        SettlementMustNotBeHostile = true,
        SettlementType = "Southern",
        TimeOfDay = "Day",
    },
    {
        EventID = "event.cannon_execution",
        FileName = "cannon_execution_event.nut",
        NumberOfOpenRosterSlots = 1,
        RequiredDLC = ["Blazing Deserts"],
        TileRequirements = { TerrainType = "Desert", TacticalType = "DesertHills", Road = "OnRoad" },
    },
    {
        BackgroundsUnlockingExtraInteractions = [{ background = "cultist", minLevel = 0, maxLevel = 0 }, { background = "converted_cultist", minLevel = 0, maxLevel = 0 }],
        EventID = "event.cultish_arrangement",
        FileName = "cultish_arrangement_event.nut",
        MinDistanceFromSettlement = 8,
        MinimumDays = 10,
        NumberOfEmptyInventorySlots = 1,
        PlayerCharacterExcluded = true,
        RequiredDLC = ["Blazing Deserts"],
        TileRequirements = { TerrainType = "Desert" },
        TimeOfDay = "Night",
    },
    {
        EventID = "event.cultural_conflagration",
        FileName = "cultural_conflagration_event.nut",
        MinimumBrotherCount = 6,
        RequiredDLC = ["Blazing Deserts"],
        SpecialConsiderations = ["Must have at least 1 southern and 1 northern ethnicity bro."],
    },
    {
        EventID = "event.desert_bugbite",
        ExcludedRetinue = ["Scout"],
        FileName = "desert_bugbite_event.nut",
        MinDistanceFromSettlement = 6,
        RequiredDLC = ["Blazing Deserts"],
        SpecialConsiderations = ["The lowest health brother without Strong, Tough, Lucky, or Southern ethnicity is most likely to be bitten.", "A bro that is Exhausted will not be bitten."],
        TileRequirements = { Road = "OffRoad", TerrainType = "Desert" },
    },
    {
        EventID = "event.desert_fall",
        ExcludedRetinue = ["Scout"],
        FileName = "desert_fall_event.nut",
        MinDistanceFromSettlement = 6,
        RequiredDLC = ["Blazing Deserts"],
        SpecialConsiderations = ["The lowest health brother without Strong, Tough, Lucky, and Southern ethnicity is most likely to fall.", "A bro that has a Bruised Leg will not fall."],
        TileRequirements = { Road = "OffRoad", TerrainType = "Desert" },
    },
    {
        EventID = "event.desert_feet",
        ExcludedOrigins = ["scenario.southern_quickstart", "scenario.manhunters"],
        ExcludedRetinue = ["Scout"],
        FileName = "desert_feet_event.nut",
        MinDistanceFromSettlement = 6,
        RequiredDLC = ["Blazing Deserts"],
        SpecialConsiderations = ["Must have 3 or more northern ethnicity bros."],
        TileRequirements = { Road = "OffRoad", TerrainType = "Desert" },
    },
    {
        EventID = "event.desert_heat",
        ExcludedRetinue = ["Scout"],
        FileName = "desert_heat_event.nut",
        MinDistanceFromSettlement = 6,
        RequiredDLC = ["Blazing Deserts"],
        SpecialConsiderations = ["The lowest health brother without Strong, Tough, Lucky, and Southern ethnicity is most likely to become Exhausted.", "A bro that has is Exhausted will not get heat stroke."],
        TileRequirements = { TerrainType = "Desert" },
        TimeOfDay = "Day",
    },
    {
        EventID = "event.desert_sand",
        ExcludedRetinue = ["Scout"],
        FileName = "desert_sand_event.nut",
        MinDistanceFromSettlement = 6,
        RequiredDLC = ["Blazing Deserts"],
        TileRequirements = { TerrainType = "Desert", Road = "OffRoad" },
        TimeOfDay = "Day",
    },
    {
        BackgroundsUnlockingExtraInteractions = [{ background = "monk", minLevel = 0, maxLevel = 0 }],
        EventID = "event.desert_well",
        FileName = "desert_well_event.nut",
        MinDistanceFromSettlement = 7,
        NumberOfEmptyInventorySlots = 1,
        NumberOfOpenRosterSlots = 1,
        RequiredDLC = ["Blazing Deserts"],
        TileRequirements = { TerrainType = "Desert", TacticalType = "DesertHills", Road = "OnRoad" },
    },
    {
        BackgroundsUnlockingExtraInteractions = [{ background = "beast_slayer", minLevel = 0, maxLevel = 0 }],
        EventID = "event.dried_oasis",
        FileName = "dried_oasis_event.nut",
        MinDistanceFromSettlement = 9,
        PlayerCharacterExcluded = true,
        RequiredDLC = ["Blazing Deserts"],
        TileRequirements = { TerrainType = "Desert", TacticalType = "DesertHills", Road = "OffRoad" },
    },
    {
        BackgroundsUnlockingExtraInteractions = [{ background = "juggler", minLevel = 0, maxLevel = 0 }],
        EventID = "event.fire_juggler",
        FileName = "fire_juggler_event.nut",
        MaxDistanceFromSettlement = 4,
        PlayerCharacterExcluded = true,
        RequiredDLC = ["Blazing Deserts"],
        SettlementMustNotBeHostile = true,
        SettlementType = "Southern",
        TimeOfDay = "Day",
    },
    {
        BackgroundRequirements = [{ background = "gladiator", minLevel = 0, maxLevel = 0 }],
        EventID = "event.gladiators_food",
        FileName = "gladiators_food_event.nut",
        RequiredDLC = ["Blazing Deserts"],
        RequiredOrigins = ["scenario.gladiators"],
        SpecialConsiderations = ["Requires only food stacks valued at 84 or fewer crowns."],
    },
    {
        BackgroundRequirements = [{ background = "gladiator", minLevel = 0, maxLevel = 0, IsPlayerCharacter = "" }],
        EventID = "event.gladiators_vibes",
        FileName = "gladiators_vibes_event.nut",
        RequiredDLC = ["Blazing Deserts"],
        RequiredOrigins = ["scenario.gladiators"],
    },
    {
        EventID = "event.gunpowder_wagon",
        FileName = "gunpowder_wagon_event.nut",
        MinimumCrowns = 2501,
        NumberOfEmptyInventorySlots = 1,
        RequiredDLC = ["Blazing Deserts"],
        TileRequirements = { TerrainType = "Desert, Oasis", TacticalType = "DesertHills", Road = "OnRoad" },
    },
    {
        EventID = "event.merchant_of_jugs",
        FileName = "merchant_of_jugs_event.nut",
        MinimumCrowns = 151,
        RequiredDLC = ["Blazing Deserts"],
        TileRequirements = { TerrainType = "Desert", TacticalType = "DesertHills", Road = "OnRoad" },
    },
    {
        BackgroundsUnlockingExtraInteractions = [{ background = "fisherman", minLevel = 0, maxLevel = 0 }],
        EventID = "event.pirates",
        FileName = "pirates_event.nut",
        NumberOfOpenRosterSlots = 1,
        RequiredDLC = ["Blazing Deserts"],
        SpecialConsiderations = ["Manhunters origin must have 2 open roster slot."],
        TileRequirements = { TerrainType = "Desert", TacticalType = "DesertHills", Road = "OnRoad" },
    },
    {
        BackgroundRequirements = [{ background = "historian", minLevel = 2, maxLevel = 0 }, { background = "cultist", minLevel = 9, maxLevel = 0 }],
        CandidateExcludedTraits = ["Mad"],
        EventID = "event.read_black_book",
        FileName = "read_black_book_event.nut",
        RequiredDLC = ["Blazing Deserts"],
        RequiredFlags = ["Lorekeeper is defeated"],
        RequiredItems = ["The Black Book"],
    },
    {
        BackgroundsUnlockingExtraInteractions = [{ background = "gladiator", minLevel = 0, maxLevel = 0 }],
        EventID = "event.retired_gladiator",
        FileName = "retired_gladiator_event.nut",
        MaxDistanceFromSettlement = 4,
        MinimumCrowns = 1251,
        NumberOfEmptyInventorySlots = 1,
        NumberOfOpenRosterSlots = 1,
        RequiredDLC = ["Blazing Deserts"],
        SettlementMustNotBeHostile = true,
        SettlementType = "Southern",
    },
    {
        EventID = "event.runaway_harem",
        FileName = "runaway_harem_event.nut",
        MinDistanceFromSettlement = 7,
        RequiredDLC = ["Blazing Deserts"],
        TileRequirements = { TerrainType = "Desert", TacticalType = "DesertHills", Road = "OnRoad" },
    },
    {
        BackgroundsUnlockingExtraInteractions = [{ background = "peddler", minLevel = 0, maxLevel = 0 }],
        EventID = "event.sellsword_retires",
        FileName = "sellsword_retires_event.nut",
        NumberOfEmptyInventorySlots = 2,
        RequiredDLC = ["Blazing Deserts"],
        TileRequirements = { Road = "OnRoad" },
    },
    {
        BackgroundsUnlockingExtraInteractions = [{ background = "wildman", minLevel = 0, maxLevel = 0 }],
        EventID = "event.sellsword_vs_bees",
        FileName = "sellsword_vs_bees_event.nut",
        MinDistanceFromSettlement = 6,
        PlayerCharacterExcluded = true,
        RequiredDLC = ["Blazing Deserts"],
        TileRequirements = { TerrainType = "Desert", TacticalType = "DesertHills" },
    },
    {
        EventID = "event.sword_eater",
        FileName = "sword_eater_event.nut",
        MaxDistanceFromSettlement = 4,
        MinimumCrowns = 101,
        NumberOfEmptyInventorySlots = 1,
        RequiredDLC = ["Blazing Deserts", "Beasts & Exploration"],
        SettlementMustNotBeHostile = true,
        SettlementType = "Southern",
        SpecialConsiderations = ["Warriors of the North DLC & a Wildman in the roster can unlock a special Wildman interaction 1 time."],
        TimeOfDay = "Day",
    },
    {
        BackgroundRequirements = [{ background = "none", minLevel = 0, maxLevel = 0 }],
        CandidateRequiredTraits = ["Mad"],
        EventID = "event.trade_black_book",
        FileName = "trade_black_book_event.nut",
        RequiredDLC = ["Blazing Deserts"],
        RequiredFlags = ["Lorekeeper is defeated"],
        RequiredItems = ["The Black Book"],
        SpecialConsiderations = ["The Peasant Militia origin qualifies without having a bro with the Mad Trait.", "The Peasant Militia origin skips the Read Black Book event."],
    },
    {
        EventID = "event.traveler_south",
        FileName = "traveler_south_event.nut",
        MinDistanceFromSettlement = 7,
        RequiredDLC = ["Blazing Deserts"],
        TileRequirements = { Road = "OnRoad", OnOrBelowYLine = 20 },
    },
    {
        EventID = "event.crisis.holywar_crucified_1",
        FileName = "holywar_crucified_1_event.nut",
        MinDistanceFromSettlement = 6,
        NumberOfOpenRosterSlots = 1,
        RequiredCrises = "Holy War",
        RequiredDLC = ["Blazing Deserts"],
        TileRequirements = { TerrainType = "Desert, Oasis", TacticalType = "DesertHills" },
    },
    {
        EventID = "event.crisis.holywar_flavor_north_outside",
        FileName = "holywar_flavor_north_outside_event.nut",
        MinDistanceFromSettlement = 6,
        RequiredCrises = "Holy War",
        RequiredDLC = ["Blazing Deserts"],
        TileRequirements = { BelowYLine = 70, Road = "OnRoad", TerrainType = "Desert, Oasis" },
    },
    {
        EventID = "event.crisis.holywar_flavor_north_settlement",
        FileName = "holywar_flavor_north_settlement_event.nut",
        MaxDistanceFromSettlement = 5,
        RequiredDLC = ["Blazing Deserts"],
        SettlementMustNotBeHostile = true,
        SettlementType = "Northern",
    },
    {
        EventID = "event.crisis.holywar_flavor_south_outside",
        FileName = "holywar_flavor_south_outside_event.nut",
        MinDistanceFromSettlement = 6,
        RequiredCrises = "Holy War",
        RequiredDLC = ["Blazing Deserts"],
        TileRequirements = { TerrainType = "Desert, Oasis, Steppe", TacticalType = "DesertHills", Road = "OnRoad" },
    },
    {
        EventID = "event.crisis.holywar_flavor_south_settlement",
        FileName = "holywar_flavor_south_settlement_event.nut",
        MaxDistanceFromSettlement = 5,
        RequiredDLC = ["Blazing Deserts"],
        SettlementMustNotBeHostile = true,
        SettlementType = "Southern",
    },
    {
        EventID = "event.holywar_ill_southerners",
        FileName = "holywar_ill_southerners_event.nut",
        MaxDistanceFromSettlement = 20,
        MinDistanceFromSettlement = 7,
        RequiredCrises = "Holy War",
        RequiredDLC = ["Blazing Deserts"],
        TileRequirements = { TerrainType = "Desert, Steppe", AboveYLine = 20 },
        TimeOfDay = "Day",
    },
    {
        BackgroundsUnlockingExtraInteractions = [{ background = "wildman", minLevel = 0, maxLevel = 0 }],
        EventID = "event.holywar_neutral_nomads",
        ExcludedOrigins = ["scenario.manhunters", "scenario.gladiators", "scenario.southern_quickstart"],
        FileName = "holywar_neutral_nomads_event.nut",
        MinDistanceFromSettlement = 7,
        RequiredCrises = "Holy War",
        RequiredDLC = ["Blazing Deserts"],
        TileRequirements = { TerrainType = "Desert", TacticalType = "DesertHills", Road = "OffRoad" },
    },
    {
        EventID = "event.holywar_sand_storm",
        FileName = "holywar_sand_storm_event.nut",
        MinDistanceFromSettlement = 8,
        RequiredCrises = "Holy War",
        RequiredDLC = ["Blazing Deserts"],
        TileRequirements = { TerrainType = "Desert" },
        TimeOfDay = "Day",
    },
    {
        EventID = "event.crisis.holy_warnings",
        FileName = "holywar_warnings_event.nut",
        MinDistanceFromSettlement = 5,
        RequiredCrises = "Holy War",
        RequiredCrisesStatus = "Warning",
        RequiredDLC = ["Blazing Deserts"],
        TileRequirements = { Road = "OnRoad" },
    }
];